import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "./components/app-sidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Flex container for Sidebar and Main Content */}
        <div className="flex h-screen">
          {/* Sidebar takes fixed width */}
          <SidebarProvider>
   
            <AppSidebar />
  
            {/* Main content takes remaining space */}
            <main className="flex-1 bg-gradient-to-b from-white to-[#1c6efc]/15 overflow-auto p-6">
            <SidebarTrigger/>
              {children}
            </main>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
